Mgnr list payment
ecomplus/app-mercadopago pull request #119
Opened 2022-02-25 17:08 UTC by matheusgnreis

2022-02-25 20:53 UTC, matheusgnreis commented
@leomp12

2022-02-25 22:32 UTC, leomp12 requested changes

2022-02-25 22:32 UTC, leomp12 commented on functions/ecom.config.js
> +            description: 'Valor mínimo para habilitar forma de pagamento',
```suggestion
            description: 'Valor mínimo para habilitar pagamento por boleto',
```

2022-02-25 22:32 UTC, leomp12 commented on functions/ecom.config.js
> +      description: 'Valor mínimo para habilitar forma de pagamento',
```suggestion
      description: 'Valor mínimo para habilitar pagamento por cartão',
```

2022-02-25 22:32 UTC, leomp12 commented on functions/routes/ecom/modules/list-payments.js
> +    if (methodConfig && ((methodConfig.enable && isMinAmount) || (isCreditCard && !methodConfig.disable && isMinAmount))) {
`methodConfig.min_amount` não necessariamente vai estar definido, principalmente pra quem já tinha o app instalado, se desse merge assim as lojas que têm MP atualmente ficariam sem a forma de pagamento 😆

2022-02-25 22:32 UTC, leomp12 commented on functions/routes/ecom/modules/list-payments.js
> +    if (methodConfig && ((methodConfig.enable && isMinAmount) || (isCreditCard && !methodConfig.disable && isMinAmount))) {
fora isso seu if ficou meio fein repetindo o `&& isMinAmount` desnecessariamente..

2022-02-25 22:32 UTC, leomp12 commented on functions/routes/ecom/modules/list-payments.js
> +    if (methodConfig && ((methodConfig.enable && isMinAmount) || (isCreditCard && !methodConfig.disable && isMinAmount))) {
```suggestion
    if (
      methodConfig &&
      (methodConfig.enable || (isCreditCard && !methodConfig.disable)) &&
      !(methodConfig.min_amount > amount.total)
    ) {
```

2022-03-03 19:58 UTC, leomp12 approved these changes
boa boa 👍🏾

2022-03-03 19:59 UTC, merged